### ISSUE TITLE
about different search depth

### ISSUE THREAD

**Issue by OpenZYK** [GovernmentCommunicationsHeadquarters/Gaffer#141]
Hi all,

In our scene, we focus on the query's QPS for the database, so we want to compare gaffer with neo4j, Titan to obtain the performance indicator in different search depth,

but I don't find the API for 2-level depth relations, 3-level depth relations and 4-level depth relations. Could you tell me how to do it ? 

By the way , could I blind the tinkerpop to gaffer ? Could gaffer support the query language,such as, gremlin or sparkql ? 

Thanks.

**Comment by p013570** [comment]
A Gaffer Graph exposes a method to execute a single operation or a chain of operations. For example, if you wanted to start at a vertex 'vertex1' and traverse along 3 edges and get the vertices at the end you can build up an operation chain using 3 GetAdjacentEntitySeeds operations. This can be written directly in Java and executed directly on the Graph or in JSON and execute via the REST API.

```java
final OperationChain<Iterable<EntitySeed>> operationChain = new OperationChain.Builder()
    .first(new GetAdjacentEntitySeeds.Builder()
        .addSeed(new EntitySeed("vertex1"))
        .build())
    .then(new GetAdjacentEntitySeeds())
    .then(new GetAdjacentEntitySeeds())
    .build();
```

```json
{
    "operations" : [ 
    {
        "class" : "gaffer.operation.impl.get.GetAdjacentEntitySeeds",
        "seeds" : [ 
            {
              "gaffer.operation.data.EntitySeed" : {
                "vertex" : "vertex1"
              }
            } 
        ]
    }, 
    {
        "class" : "gaffer.operation.impl.get.GetAdjacentEntitySeeds"
    }, 
    {
        "class" : "gaffer.operation.impl.get.GetAdjacentEntitySeeds"
    } 
  ]
}
```

I'm assuming you will be running your performance test on the Accumulo implementation, however please note that as Gaffer is a framework you could actually write a Neo4J or Titan implementation of Gaffer.


We are currently working on a lightweight TinkerPop implementation of Gaffer (gh-110) - it will simply wrap Gaffer in the TinkerPop API. There will be a few limitations due to Gaffer not currently supporting edits, deletes or fetch all elements without a seed. But from our initial investigations it looks like it will work quite well. We hope to have the code pushed up in the near future.

**Comment by OpenZYK** [comment]
excuse me, I have a problem when only the iterator only once next () method, query time an entity takes about four seconds, two entities query time takes about six seconds, is there any way to optimize it?
One hundred and fifty million of data stored in Accumulo, Accumulo node has eight, JVM heap size is 4G

**Comment by p013570** [comment]
Assuming your question has been answered, please reopen the issue if you need to.
