### ISSUE TITLE
Could we change zookeeper instance or caching it?

### ISSUE THREAD

**Issue by OpenZYK** [GovernmentCommunicationsHeadquarters/Gaffer#144]
Hi,

In the code below, we find constructing the ZooKeeper instance is very time-consuming, but when the getConnector function is called every time, the ZooKeeper instance will be reconstructed.

here the ZooKeeper instance is a local object, could we change it into a global one or Cache the Object? 

By the way, by Caching the hbase connection object, we can speed up the query process.

Thank you very much! 

gaffer.accumulostore.utils.TableUtils

```
public static Connector getConnector(final String instanceName, final String zookeepers, final String userName,final String password) throws StoreException {
        final Instance instance = new ZooKeeperInstance(instanceName, zookeepers);
        try {
            return instance.getConnector(userName, new PasswordToken(password));
        } catch (AccumuloException | AccumuloSecurityException e) {
            throw new StoreException("Failed to create accumulo connection", e);
        }
    }
```

**Comment by james010101101** [comment]
I've made a change relating to this on the G144 branch.
I've cached the Connector object inside a store instance, meaning if you can maintain access to the same store instance like in an operation chain you only need to create the zkInstance once. The Connector object its-self can handle multiple threads/operations.
The zkInstance is still re-created if a new store instance is created (e.g by a second user) or the underlying getConnection method is called (currently all all but 1 calls pass through the getConnection method on the AccumuloStore class) this is worth keeping because it is good to check that the zookeeper nodes are still available in this case rather than relying on older connections.

**Comment by p013570** [comment]
Merged into develop.
