### ISSUE TITLE
Gaffer not building in Windows

### ISSUE THREAD

**Issue by pranita-s** [GovernmentCommunicationsHeadquarters/Gaffer#159]
Hi,
I tried to build Gaffer in Windows so that I could import it in an IDE so that I can run them as Java applications. But its not building.
But it builds successfully in Ubuntu.
Can Gaffer work on only Linux based machines ?

**Comment by p013570** [comment]
Hi @pranita-s 

We have just attempted to build the project on a Windows environment and as you correctly pointed out it fails. From a quick glance at the errors, it looks like there are several issues due to different new line encodings on Windows and Unix. 

I have raised an issue, gh-164, to make the maven build compatible with Windows in the future. So unfortunately for the time being it will need to be built on a Unix environment.

Additionally, until we have been able to further test running the application on Windows, we recommend that it is also run on a Unix environment.

**Comment by p013570** [comment]
Closing this bug as it will be fixed by issue gh-164.
