### ISSUE TITLE
wrap the tinkerpop to gaffer

### ISSUE THREAD

**Issue by dongxinghua** [GovernmentCommunicationsHeadquarters/Gaffer#192]
we want to use gaffer in our project and I have to wrap the tinkerpop to gaffer,  we know you are doing it, could you give us a development schedule ? Thank you very much!

**Comment by p013570** [comment]
Hi @dongxinghua,

We have created a lightweight Gaffer implementation of TinkerPop in issue gh-110. This is due to be released within the next couple of weeks. It is included in [0.3.5-RC1]( https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/tree/gaffer2-0.3.5-RC1) (release candidate 1), as soon as this has been tested it would be released as part of version 0.3.5.

There is a [README]( https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/tree/gaffer2-0.3.5-RC1/tinkerpop) for the TinkerPop implementation, that explains how to use it. Please note it is still experimental and should be used with caution.

As it is very early days with this TinkerPop implementation we would appreciate any feedback you have on it.
