### ISSUE TITLE
License

### ISSUE THREAD

**Issue by evanplaice** [GovernmentCommunicationsHeadquarters/Gaffer#3]
If this project is paid for by public funding, why isn't it licensed under the public domain?
https://creativecommons.org/publicdomain/zero/1.0/

**Comment by l1x** [comment]
What is wrong with Apache License Version 2.0 exactly?

**Comment by iand** [comment]
In the UK, government funded work is under Crown Copyright rather than public domain. Crown Copyright has almost no restrictions except the government retains copyright. In practice this is as reusable as it would be if it were in the public domain but, in principle, the government can enforce copyright if it wanted to, which some might say could happen if the government wanted to manufacturer a legal position against a particular group or individual.

An agency can additionally state that the work is available under the Open Government Licence which is compatible with the Creative Commons Attribution license. I encourage the owners of the Gaffer repository to state that the code and documentation is also available under the OGL by following the guidance [here](http://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/licensing-for-re-use/guidance-for-information-providers/make-information-available-ogl/)

**Comment by evanplaice** [comment]
@iand Thanks for clearing that up.

In the US, public domain applies. That's what ['18f'](https://github.com/18F) and the ['US Digital Service'](https://github.com/usds) use.

Since it's a government sourced project, it might be desirable to set a good precedent by using the government-specific open license.

**Comment by evanplaice** [comment]
On an unrelated note, since it's appears to be bundled with Apache Cumulo derivatives the project will need to retain the NOTICE(s) from that project.

Disclaimer: IANAL, just a guy who has spent a lot of time researching open licenses to cover my own backside.

**Comment by gaffer01** [comment]
@iand Thank you for your comment. We have taken advice and are happy that the Apache License is appropriate for this project, and do not think that additionally releasing it under the OGL would provide extra benefit to software developers.

**Comment by evanplaice** [comment]
@gaffer01 :+1:
