### ISSUE TITLE
Stuck in running programs

### ISSUE THREAD

**Issue by sterkhedkar** [GovernmentCommunicationsHeadquarters/Gaffer#30]
I have built Gaffer and have Accumulo running on Hadoop on Ubuntu instance. 

But I am having trouble with running the programs. It will be helpful if you could guide me about how to exactly run programs using Maven or there is some other way ??
And I am awaiting the User Guide !

**Comment by james010101101** [comment]
Hi @sterkhedkar,

Maven is a tool used to build gaffer it can't be used to run gaffer.
In order to run gaffer you will need to create some “client” code,
I suggest you start by looking at the example folder in the project to get a feel for how to write code to interact with gaffer.
If you look at our simple query example here:

https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/blob/master/example/src/main/java/gaffer/example/SimpleQuery.java

You can use this as a template for your own code.

We also have a getting started guide on a branch here:

https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/blob/G14-user-guide/docs/getting_started.md

This relates to the example project and should introduce you to things like writing schemas for your data.

We are still working on a full user guide

Hope this helps.

**Comment by james010101101** [comment]
As its been over 7 days without a response this issue will be closed.
