### ISSUE TITLE
Accumulo iterators next() methods need to return the next element

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#38]
See AbstractElementIteratorReadIntoMemory and AbstractElementIteratorFromBatches.

Currently multiple calls to next() will keep returning the same element. In order to use the iterators users must call hasNext() before calling next(). 

Also calling hasNext() multiple times before calling next() will skip elements.

**Comment by james010101101** [comment]
This is expected behaviour, 
The client side check on if both ends of an edge are valid for set retrievers executes on the client side to check that no incorrect Edges (Not within/between the sets) got through the bloom filter.
Calling .hasNext() without this check would simply be able to tell you if another Element existed in the accumulo scanner, not if there was a valid Element left.
If you were to call .next() and then do the check there, you could get the next Element, check to see if that Element was valid and then find that it wasn't, discard that Element but then find that the iterator has no more Elements left to check, whereupon you would be forced to return null or the last Element again, after the iterator having told you that there was another Element with the .hasNext() method.

**Comment by p013570** [comment]
Merged into develop.
